### PR TITLE
Ignore grants

### PR DESCRIPTION
**Pull request by marksabincarnivaluk**
Hi,
For your review and feedback.
We have briefly discussed the problems with clones before, under an issue I raised. I have implemented a work-around in the role resolver that skips any grants where the name begins with the name of my clone database. I'm now trying to generalise this solution for all non-SnowDDL-managed databases.

Summary:
Ignore grants on objects in databases that SnowDDL does not manage. Grants on objects in databases that are not in _config folder are ignored during the resolver process. This allows clones of SnowDDL-managed databases to be taken (and owned by a different role), without causing SnowDDL to process a large number of revokes against the cloned database.

### CODE REVIEW

**Comment by littleK0i** [comment]
This approach might seem like a good idea at first, but it will prevent valid `REVOKE` commands from happening in the following cases:

1. Database was renamed or swapped with another database;
2. Some external privileges were granted to role managed by SnowDDL, accidentally or maliciously;

It also breaks the fundamental idea of SnowDDL producing exactly the same state of managed objects, roles and permissions regardless of initial state of Snowflake account.

---

I see the following potential alternatives:

1. When you create a cloned database, you may also swap SnowDDL grants on its objects with "dev" grants. This article describes the idea quite well: https://medium.com/snowflake/rbac-and-cloning-for-devops-950c800c594e

2. It might be possible to define names of cloned databases explicitly as an option in `DATABASE` config (`params.yaml` file): https://docs.snowddl.com/basic/yaml-configs/database. Grants on cloned objects can be ignored, as well as many other cloning issues which will be discovered in future.

---

However, I am not sure if its even worth pursing the idea of database cloning instead of creating real DEV / QA environments with env_prefix and / or multiple Snowflake accounts. You'll probably struggle with various issues for months and eventually be forced to switch to the proper implementation.

This feature looks good in marketing materials, but it's barely useable in real world due to high amount of limitations and "gotchas".

**Comment by marksabincarnivaluk** [comment]
Hi,
Even with the various caveats of cloning taken into consideration, we and many others find clones useful. One particular use-case is creating short-lived databases to carry out tasks such as testing deployments. Clones have the benefit of bringing the data with them, vs having to copy the data, and being short-lived means there is no maintenance, for example rolling back failed releases.
I like your option 2. I had considered a config option initially. I'll rework my code that way and I hope you will consider it for inclusion in the main project.

**Comment by littleK0i** [comment]
An another possible solution:

1. Create empty DEV databases and schemas for cloned objects with flag `is_sandbox: true`.
2. Create separate business roles and users for testing. Grant schema roles from DEV database to test users.
3. Clone each object from PROD database to DEV database individually 1-by-1 with `CREATE <object> ... CLONE`. Do not add `COPY GRANTS` while doing so.

In theory, if `COPY GRANTS` are not used during cloning, normal future grants from schema roles should take over. You'll get the copy of data with correctly configured permissions.

Potential problems:
- Tech roles will be missing for DEV database objects.
- Objects in DEV database should be dropped manually. It can be done in the same script which does cloning.

**Comment by marksabincarnivaluk** [comment]
Thanks, I'll give that approach a try.

**Pull request closed without merging**
