### PR TITLE
oauth authentication for snowpark

### PR DESCRIPTION
**Pull request by marksabincarnivaluk**

### CODE REVIEW

**Comment by littleK0i** [comment]
That's a strange diff. Did you enforce windows line-endings by any chance?

**Comment by marksabincarnivaluk** [comment]
Ah yes. I've pushed again. Looks better now.

**Review by littleK0i — APPROVED** [review]

**Comment by littleK0i** [comment]
@marksabincarnivaluk , merged and changed a few things a bit.

1. Oauth authentication still requires "account" and "user" to be present. Adjusted validation accordingly.
2. Replaced raw `isfile` and `read` calls with `Path.is_file` and `Path.read_text` calls from `pathlib`. Basically an entire SnowDDL uses `pathlib` for everything.

Available since `0.37.3`.

**Comment by marksabincarnivaluk** [comment]
@littleK0i, account is required, but user is not required and passing in a user actually results in an error:

snowflake.connector.errors.DatabaseError: 250001 (08001): Failed to connect to DB: snowflake.eu-west-1.snowflakecomputing.com:443. The user you were trying to authenticate as differs from the user tied to the access token.

SF docs reference:
https://docs.snowflake.com/en/developer-guide/snowpark-container-services/additional-considerations-services-jobs#connecting-to-snowflake

**Comment by littleK0i** [comment]
@marksabincarnivaluk , does it fail if you leave user empty and let it to be collected automatically from `SNOWFLAKE_USER` env?

Is user in ENV still "different"?

**Comment by marksabincarnivaluk** [comment]
It fails if you don't pass a user. Snowpark container doesn't auto-create SNOWFLAKE_USER env var, only those listed below.
My original version worked without passing the user. This version I can work around by passing SNOWFLAKE_SERVICE_NAME as the user since that is the user that the token is generated for, but seems like an unnecessary step since it works fine without passing a user.

SNOWFLAKE_ACCOUNT
SNOWFLAKE_DATABASE
SNOWFLAKE_HOST
SNOWFLAKE_PORT
SNOWFLAKE_SCHEMA
SNOWFLAKE_SERVICE_NAME

**Comment by littleK0i** [comment]
@marksabincarnivaluk , that's a bit odd, but alright.

Relaxed validation condition in `0.37.4`. Now it checks only for "a" (account) to be present for `oauth_snowpark`.

**Comment by marksabincarnivaluk** [comment]
Thanks, now working perfectly.

**Pull request merged**
